### ISSUE TITLE
validation doesn't work for array elements

### ISSUE THREAD

**Issue by laurentpayot** [jagi/meteor-astronomy-validators#13]
I'm trying to set validators for an array of tags but it doesn't seem to work. Am I doing it the right way?

(I'm quickly pasting my _CoffeeScript_ code, hope you don't mind...)

<pre>
V = Validators
@Foos = new Mongo.Collection('foos')
@Foo = Astro.Class(
    name: 'Foo'
    collection: Foos
    fields:
        'tags':
            type: 'array'
            default: []
            index: true
            validators: [V.required(), V.array(), V.maxLength(100)]
        'tags.$':
            type: 'object'
            default: {}
            validators: [V.object()]
        'tags.$.tag':
            type: 'string'
            validators: [V.required(), V.string(), V.minLength(2), V.maxLength(20)]
)
</pre>

When I validate it in Meteor shell I get the following:

<pre>
> f = new Foo({tags:[1]})
{ _values: { tags: [ 1 ], _id: null },
  _original: { _id: null },
  _isNew: true,
  _errors: 
   { _size: 0,
     _values: {},
     _sizeDeps: { _dependentsById: {} },
     _allDeps: { _dependentsById: {} },
     _keysDeps: { _dependentsById: {} },
     _valuesDeps: { _dependentsById: {} },
     _keyDeps: {},
     _hasDeps: {} } }
> f.validate()
true
> f = new Foo({tags:[""]})
{ _values: { tags: [ '' ], _id: null },
  _original: { _id: null },
  _isNew: true,
  _errors: 
   { _size: 0,
     _values: {},
     _sizeDeps: { _dependentsById: {} },
     _allDeps: { _dependentsById: {} },
     _keysDeps: { _dependentsById: {} },
     _valuesDeps: { _dependentsById: {} },
     _keyDeps: {},
     _hasDeps: {} } }
> f.validate()
true
>
</pre>

**Comment by lukejagodzinski** [comment]
Hi, you have an error in you code. You've defined the `tags.$.tag` validator as the field instead validator. Nested validators have to be defined under the `validators` property in the schema.

In fact the way you define nested fields and validators will change in the next release which is going to be published soon.

**Comment by laurentpayot** [comment]
Thanks for your quick answer. I'm closing the issue, waiting for the next release then... :hourglass:

**Comment by lukejagodzinski** [comment]
And to make it clear for all I will post the correct code:

``` js
var V = Validators;

Foos = new Mongo.Collection('foos');
Foo = Astro.Class({
  name: 'Foo',
  collection: Foos,
  fields: {
    'tags': {
      type: 'array',
      default: [],
      index: true,
      validators: [V.required(), V.array(), V.maxLength(100)]
    },
  validators: {
    'tags.$': [V.object()],
    'tags.$.tag': [V.required(), V.string(), V.minLength(2), V.maxLength(20)]
  }
});
```

**Comment by laurentpayot** [comment]
:+1:
