### ISSUE TITLE
Returning a nested date for the lt, lte, gt and gte validators

### ISSUE THREAD

**Issue by ghost** [jagi/meteor-astronomy-validators#18]
I was wondering if there's anyway to return a nested value inside a compareValue for the comparaison validators like `Validators.lt()`.

For example, i've got two dates, and i need to know if the first one is before the second one. The problem being that those date are inside an array of objects like this:

```
'schedules.$.monday.morning_start': {
            type: 'date',
            validators: [
                Validators.required(),
                Validators.date(),
                Validators.lt(function(){
                    return this.schedules.$.monday.morning_end;
                })
            ]
     }
```

This example doesn't work because of the `$`, and that's the one i need to replace by the proper array index. And it does and up working if i use:
`return this.schedules[0].monday.morning_end`
Which isn't really useful...

**Comment by lukejagodzinski** [comment]
Hi, it was already implemented in the new version :-). So a lot of new features will appear :-)

**Comment by lukejagodzinski** [comment]
In closing this issue for now :-)

**Comment by ghost** [comment]
Awesome. Thanks ;). Will wait for this new version then.
