### ISSUE TITLE
Required validator ?

### ISSUE THREAD

**Issue by vladshcherbin** [jagi/meteor-astronomy-validators#2]
I guess, there is no **required** validator?

We need that.

**Comment by lukejagodzinski** [comment]
There is a required validator but it's an alias to isNotNull validator. Maybe I should do otherwise. And the error message is "it can't be null", so I will change it to "is required".

**Comment by vladshcherbin** [comment]
@jagi oh, thanks, didn't see it. There is a required alias so it is okay. The required message would be a nice replacement!
