### ISSUE TITLE
How to clear validation errors manually?

### ISSUE THREAD

**Issue by tsega** [jagi/meteor-astronomy-validators#22]
Is there a way to manually clear validation errors? It looks like the `_errors` property holds the errors but setting that to `null` results in an error.

**Comment by lukejagodzinski** [comment]
The `_errors` property is reactive and you can't set it to null. Instead you have to call `clear()` method `doc._errors.clear()`. However, I think it should be a method on the document level like: `doc.clearValidationErrors()` or something like that.

**Comment by tsega** [comment]
Thanks @jagi, that worked like a charm! :+1:

**Comment by lukejagodzinski** [comment]
No problem :). I've already implemented the `doc.clearValidationErrors()` method that will appear in the next release (in about one month from now, in two weeks pre release version).
