### ISSUE TITLE
Errors are returned appearing unescaped

### ISSUE THREAD

**Issue by andykingking** [jagi/meteor-astronomy-validators#28]
Validation errors are returned appearing unescaped. For example:

**Original**
`Validators.gte(10, "Requires at least 10 characters")`
**Output**
`"Requires at least 10 characters"`

**Original**
`Validators.lte(128, 'The "field" field requires at most "128" characters')`
**Output**
`"The \"field\" field requires at most \"128\" characters"`

**Comment by lukejagodzinski** [comment]
I've checked it and everything works correctly. Could you create reproduction repository? It would probably show the error you are making.

**Comment by andykingking** [comment]
You're right, it was my mistake. That's what I get for not reading the docs thoroughly.

Out of interest, I was using particular properties on the class instance to retrieve errors.
