### ISSUE TITLE
Cannot customize error message for "type" validators

### ISSUE THREAD

**Issue by chenghanlee** [jagi/meteor-astronomy-validators#30]
Hi Jagi,

We can't seem to set a custom error message for type validators, e.g. Validators.number, Validators.string, and etc., at their constructions.

Currently, it seems like using  "validatorError" event is the only way to return custom error message for type validators. 

It will be nice if we can customize error messages for type validators during the validator construction like we can for size validators. 

Thank you.

**Comment by lukejagodzinski** [comment]
It works you are probably passing a custom error message as the first argument of a validator and you should pass `null` as the first and an error message as the second.

``` js
// WRONG!
Validators.string('HAS TO BE STRING!');
```

``` js
// CORRECT!
Validators.string(null, 'HAS TO BE STRING!');
```

**Comment by chenghanlee** [comment]
Ah. I must have missed this in the documentation. Thank you for the explanation.

**Comment by lukejagodzinski** [comment]
No problem :-)
