### ISSUE TITLE
Is there any way I can get the list of choices defined from a field in a class?

### ISSUE THREAD

**Issue by Lepozepo** [jagi/meteor-astronomy-validators#40]
I know I could save the list outside of the context of the field but it would be cleaner if I could tap into the field list directly. Is there a method implemented for this? Thank you in advance!

**Comment by Lepozepo** [comment]
Found it under `CLASS.constructor.getValidator("field-name")` for each class, sweet!

**Comment by lukejagodzinski** [comment]
Yep exactly :)
