### ISSUE TITLE
Integer validator?

### ISSUE THREAD

**Issue by james1293** [jagi/meteor-astronomy-validators#43]
Hello,
I'm planning to write my own `integer` validator and submit it as a pull request. What category do you think I should list it as?

(If this isn't the place to ask this, let me know; I'm still new to github.)

**Comment by james1293** [comment]
Update - it looks like you already added this to astronomy 2.

https://github.com/jagi/meteor-astronomy/blob/v2/lib/modules/validators/validators/type/integer.js

I guess I'll go submit a pull request for the astronomy 2 docs :-)

**Comment by lukejagodzinski** [comment]
@james1293 thanks for noticing it! I forgot to add it to docs :). I would be glad if you create PR :). Docs are in the gh-pages branch. Thanks!
