### ISSUE TITLE
Documentation is invalid : getErrors

### ISSUE THREAD

**Issue by parhelium** [jagi/meteor-astronomy-validators#5]
It looks like in docs you are using convention : `post.getErrors()`, but in code it is undefined.
However previous version `post.getValidationErrors()` works fine. The same thing happens for other methods.

**Comment by lukejagodzinski** [comment]
Yes right, sorry for that. I can keep up correlation between documentation and the code because many things are rapidly changing. I will fix that :). Thanks for informing.

**Comment by parhelium** [comment]
Do you plan to strip word `Validation` from all methods in the future ?

**Comment by lukejagodzinski** [comment]
I had this idea but finally I've decided that the `Validation` world will stay there. Of course stripping it would make methods sorter and the code more minimalistic but I prefer descriptive method names. When seeing `getErrors`, we don't know what errors. But `getValidationErrors` is obvious. I was changing mind in this manner lately but I've chosen longer names. I hope it's now a big problem? Maybe do you have some clue, idea about naming?

**Comment by parhelium** [comment]
I like more descriptive names either. I think it is good idea to stay with `getValidationErrors` naming.

**Comment by lukejagodzinski** [comment]
Ok so I will stay with descriptive names
