### ISSUE TITLE
Validators.and() an Validators.or() are deprecated ?

### ISSUE THREAD

**Issue by parhelium** [jagi/meteor-astronomy-validators#6]
Hi @jagi  

I don't see anymore AND and OR validators. 
Have you removed them ?
If yes what is the reasoning behind ?

They are very useful!

**Comment by parhelium** [comment]
One another note.
How can I validate that could be STRING or NULL ?

In my meteor app i'm using:
jagi:astronomy@=0.9.1
jagi:astronomy-validators@=0.9.1

as new version ( 0.10.\* ) breaks a lot of code.

---

Another thing, are you using SEMVER ?

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes. 

Form my perspective you applied changes which should increase MAJOR, not MINOR field.

**Comment by lukejagodzinski** [comment]
Ok first I will write about SEMVER. SEMVER is mostly true for projects that are in version 1.0.0 and above. Right now library is in beta version. Sorry for such changes but it was also true with Meteor that many things have been changing very often until 1.0.0 came out.

I had to make validators simpler and more flexible. Thanks to the simplifications, you can now write validation function just like this one https://github.com/jagi/meteor-astronomy/wiki/Validators#custom-validator without needing to register any validator. You can just pass any function that will do a validation.

To allow that I had to make some changes and it caused problems with nested validators. I can bring back `or` validator in such form:

``` js
validators: {
  firstName: Validators.or([
    Validators.string(null, 'Has to be string!'),
    Validators.null(null, 'Has to be null!')
  ], 'Has to be string or null!')
}
```

But you won't be able to tell what validator caused error. If it was `string` or `null`. You will only get error `"Has to be string or null!"`. Are you gonna be happy with that?

And once again sorry for such breaking changes but version 1.0.0 is close :)

**Comment by lukejagodzinski** [comment]
And do you have any other use cases beside that one you've mentioned?

**Comment by lukejagodzinski** [comment]
Ok AND and OR validators are back. Let me know if there are any use cases where you would like to now what nested validator caused error.

**Comment by parhelium** [comment]
Thank you @jagi !

**Comment by ghost** [comment]
I got a problem with or and and validators. I got a field that can be either null or if not, has to validate through a few validators. I tried this way, but it doesn't work. Maybe my syntax is wrong ? 

```
reference: {
            type: 'string',
            validators: Validators.or(
                Validators.null(),
                Validators.and(
                    Validators.string(),
                    Validators.minLength(2),
                    Validators.maxLength(50)
                )
            )
        }
```

Basically, if my value is null, the validation is ok, but if i have a value, and, for example, it's only one character long, it doesn't throw the minLength error...

**Comment by lukejagodzinski** [comment]
From what I remember you have to reverse order:

``` js
validators: Validators.or(
  Validators.and(
    Validators.string(),
    Validators.minLength(2),
    Validators.maxLength(50)
  ),
  Validators.null()
)
```

It should work, let me know.

In the new version there will be the `required` field's attribute that will replace `Validators.required()` validator. If the `required` attribute is set to `false` then the field will accept a `null` value on validation. If the `required` attribute is set to `true` then a validation will take place and depending on your validation rules it will return proper error. It will look as follows:

``` js
fields: {
  reference: {
    type: 'string',
    required: false,
    validators: [
      Validators.string(),
      Validators.minLength(2),
      Validators.maxLength(50)
    ]
  }
}
```

It will be much simpler approach.

**Comment by ghost** [comment]
Unfortunately, it doesn't work either way. If i use only the simple validation, it works ok, but with 'or', it just doesn't send anything back.

**Comment by ghost** [comment]
With further testing, i found out it actually simply pass the validation, not matter what i write in the input...

**Comment by lukejagodzinski** [comment]
I've just noticed that you have an error in your code and I blindly copied it. It should be:

``` js
validators: Validators.or([
  Validators.and([
    Validators.string(),
    Validators.minLength(2),
    Validators.maxLength(50)
  ]),
  Validators.null()
])
```

Notice that I've added parentheses `[]`. I've wrapped validators list in `and` and `or` validators. That's it. I've tested it and it worked.

**Comment by ghost** [comment]
Damned, while trying to make it work, i removed those and forgot to put them back after inverting the .null() and and(). Noob mistake :dancer:

Thanks, everything works perfectly now

**Comment by lukejagodzinski** [comment]
Ok good to hear :). In the documentation of validators I will add a note that emphasizes that it has to be an array.

**Comment by ghost** [comment]
I've actually find what looks like a real problem this time (or maybe another mistake for me :D). When using the unique() validators with the or() and and() we talked about, it doesn't work. Looks like 'this' doesn't receive the Class. As a result, unique() crash on first line with :
`this.constructor.getCollection();`

**Comment by lukejagodzinski** [comment]
Hmm it maybe cause by not executing nested validator in the context of the document. I will check it tomorrow and fix it. If you find any other problem, please create separate issue :) so I will be able to track what else I have to do. It's easier to close unnecessary issue than following multiple problems in the one :)

**Comment by lukejagodzinski** [comment]
Ok it was quick fix that I've made right away. It's published and should work right now. Thanks for noticing it. However I was rewriting `and` and `or` validators in the new version and it was already fixed :)

**Comment by ghost** [comment]
Damned, i didn't even got the time to reply that it was already fixed...Everything works now. Awesome work, as always.
And yep, i'll create new issue from now on, you're right ;)

**Comment by lukejagodzinski** [comment]
Hehe :)
